# Generated by Django 2.2.2 on 2019-06-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import koboland.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=koboland.helpers.create_hash, max_length=32, unique=True)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=koboland.helpers.create_hash, max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('thread_type', models.IntegerField(choices=[(10, 'Private'), (20, 'Group'), (30, 'Public Room')], default=10)),
                ('clients', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Message')),
            ],
        ),
        migrations.CreateModel(
            name='UnreadReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.Message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.MessageThread')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.MessageThread'),
        ),
    ]
