# Generated by Django 2.2.2 on 2019-06-16 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=r'CREATE UNIQUE INDEX name_upper_idx ON main_board(UPPER(name));',
            reverse_sql=r'DROP INDEX name_upper_idx;'
        ),
    ]
