# Generated by Django 2.2.2 on 2019-06-14 15:55

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20190614_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=main.models.get_file_path)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(to='main.SubmissionMedia'),
        ),
        migrations.AddField(
            model_name='topic',
            name='files',
            field=models.ManyToManyField(to='main.SubmissionMedia'),
        ),
    ]
