# Generated by Django 2.2.2 on 2019-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190622_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
