# Generated by Django 2.2.2 on 2019-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20190612_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
