# Generated by Django 2.2.2 on 2019-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20190619_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
