# Generated by Django 2.2.2 on 2019-06-14 18:42

from django.db import migrations, models

import main.models
import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20190614_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmedia',
            name='file',
            field=models.FileField(upload_to=main.models.get_file_path, validators=[main.validators.FileValidator(
                content_types=['video/mpeg', 'video/ogg', 'video/webm', 'image/gif', 'image/jpeg', 'image/png',
                               'image/svg+xml', 'image/tiff', 'image/webp', 'image/bmp'])]),
        ),
    ]
