# Generated by Django 2.2.2 on 2019-06-17 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmedia',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='display_picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike'), (0, 'NoVote')], default=0),
        ),
    ]
