# Generated by Django 2.2.2 on 2019-06-14 19:07

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20190615_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmedia',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='file',
            field=models.FileField(upload_to=main.models.get_file_path),
        ),
    ]
